=== kaetojn/Website/PFW/Games/project-team10-master/301Project/src/recources/questions.dtd
<!ELEMENT questions (true-false-questions, return-value-questions)>
<!ELEMENT true-false-questions (question*)>
<!ELEMENT return-value-questions (question*)>
<!ELEMENT question (ask, answer, types?, hint*)>
<!ATTLIST question difficulty (1|2|3|4|5) #REQUIRED>
<!ELEMENT ask (#PCDATA)>
<!ELEMENT answer (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT types (VAR?, ARITHMETIC?, LIST?, FOR?, WHILE?, CALL?)>
<!ELEMENT VAR EMPTY>
<!ELEMENT ARITHMETIC EMPTY>
<!ELEMENT LIST EMPTY>
<!ELEMENT FOR EMPTY>
<!ELEMENT WHILE EMPTY>
<!ELEMENT CALL EMPTY>

=== kaetojn/Website/PFW/Games/project-team10-master/301Project/src/recources/questions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE questions SYSTEM "questions.dtd">
<questions>
	<true-false-questions>
		<question difficulty="2">
			<ask>4 == 3</ask>
			<answer>false</answer>
			<types>
				<ARITHMETIC/>
			</types>
		</question>

		<question difficulty="1">
			<ask>2 == 2</ask>
			<answer>true</answer>
			<types>
				<ARITHMETIC/>
			</types>
		</question>
		<question difficulty="1">
			<ask>3 &lt; 5</ask>
			<answer>true</answer>
			<types>
				<ARITHMETIC/>
			</types>
		</question>
		<question difficulty="1">
			<ask>5 &gt; 3</ask>
			<answer>true</answer>
			<types>
				<ARITHMETIC /></types>
		</question>
		<question difficulty="1">
			<ask>'orange' &gt; 'apple'</ask>
			<answer>true</answer>
			<types>
				<ARITHMETIC /></types>
		</question>
		
		<question difficulty="2">
			<ask>'apple' &lt; 'banana' </ask>
			<answer>true</answer>
			<types>
				<ARITHMETIC /></types>
		</question>
		<question difficulty="2">
			<ask>type(20 / 4) == type(10 // 2)</ask>
			<answer>false</answer>
			<types>
				<VAR /></types>
		</question>
		<question difficulty="1">
			<ask>name = 'Alice' \nname is type string.</ask>
			<answer>true</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="1">
			<ask>number = 2 \nnumber is type integer.</ask>
			<answer>true</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="1">
			<ask>number = 2.5 \nnumber is of type float.</ask>
			<answer>true</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="1">
			<ask>names_list =['Mary', 'Kate', 'Ashley']\nnames_list is type list</ask>
			<answer>true</answer>
			<types>
				<VAR /></types>
</question><question difficulty="2">
			<ask>number = 3.14 \nnumber is of type integer.</ask>
			<answer>false</answer>
			<types>
				<VAR /></types>
		</question>
		
		
		
		
		<question difficulty="1">
			<ask>name = 'Bob' \nThe value of the variable, name, is 'Bob'.</ask>
			<answer>true</answer>
			<types>
				<VAR /></types>
		</question>
		<question difficulty="5">
			<ask>a_list = [13, 4, 7]\nb_list = a_list.append(5)\na_list == b_list?</ask>
			<answer>false</answer>
			<types>
				<LIST />
			</types>
		</question><question difficulty="4">
			<ask>values = [3, 7, 2]\nvalues[0] == 7? </ask>
			<answer>false</answer>
			<types>
				<LIST /></types>
		</question><question difficulty="2">
			<ask>list_words = ['dog', 'cat', 'fish'] \nlist_words[0]=='dog'</ask>
			<answer>true</answer>
			<types>
				<LIST /></types>
		</question>
		<question difficulty="2">
			<ask>list_names = ['Alice', 'Bob', 'Spongebob']\nlist_names[1]=='Alice'</ask>
			<answer>false</answer>
			<types>
				<LIST /></types>
		</question>
		<question difficulty="3">
			<ask>list = ['pie', 'cake', 'candy', 'chocolate'] \nfor food in list: \n   print(food)\nPrints: \n'pie'\n'cake'\n'candy'\n'chocolate'</ask>
			<answer>true</answer>
			<types>
				<FOR /></types>
		</question>
		<question difficulty="2">
			<ask>list = [1,2,3]\nfor number in list:\n   print('hello')\nprints 'hello' 3 times</ask>
			<answer>true</answer>
			<types>
				<FOR /></types>
		</question>
		<question difficulty="2">
			<ask>list = [1,2,3,4,5]\nfor number in list:\n   print('bye')\nprints 'bye' 3 times</ask>
			<answer>false</answer>
			<types>
				<FOR /></types>
		</question>
		<question difficulty="2">
			<ask>counter=0\nwhile counter &lt; 10:\n     find buried treasure\nBuried treasure is found 10 times</ask>
			<answer>true</answer>
			<types>
				<WHILE /></types>
		</question>
		<question difficulty="3">
			<ask>counter=0\nwhile counter &lt; 10:\n     find buried treasure\nBuried treasure is found 9 times</ask>
			<answer>false</answer>
			<types>
				<WHILE /></types>
		</question>
	</true-false-questions>

	<return-value-questions>
		<question difficulty="3">
			<ask>return(20 //2 ** 2 + 3)</ask>
			<answer>8</answer>
			<types>
				<ARITHMETIC /></types>
		</question><question difficulty="1">
			<ask>return (10 / 5 * 2) \n note: return value is of type float</ask>
			<answer>4.0</answer>
			<types>
				<ARITHMETIC /></types>
		</question><question difficulty="1">
			<ask>x = 5 \n what is the value of x?</ask>
			<answer>5</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="2">
			<ask>x = 3*3 \nWhat is the value of x?</ask>
			<answer>9</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="3">
			<ask>mylist = [1, 2, 3]\nreturn mylist[0]</ask>
			<answer>1</answer>
			<types>
				<LIST /></types>
		</question>
		<question difficulty="1">
			<ask>s = "hi there"\nreturn s[3]</ask>
			<answer>t</answer>
			<types>
				<VAR /></types>
		</question><question difficulty="1">
			<ask>values = [3, 7, 2]\nvalues.append(4)\nreturn values</ask>
			<answer>[3, 7, 2, 4]</answer>
			<types>
				<LIST /></types>
</question><question difficulty="5">
			<ask>words = ['best', 'of', 'luck']\nwords.append(words[0])\nreturn words</ask>
			<answer>[’best’, ’of’, ’luck’, ’best’]</answer>
			<types>
				<LIST /></types>
		</question><question difficulty="4">
			<ask>for i in range(10)\n\tthrow a fireball\nhow many fireballs are thrown?</ask>
			<answer>10</answer>
			<types>
				<FOR /></types>
		</question>
		<question difficulty="1">
			<ask>number=0\nlist = [1,2,3]\nfor number in list:\n   number=number+1\nreturn number</ask>
			<answer>3</answer>
			<types>
				<FOR /></types>
		</question><question difficulty="3">
			<ask>i = 0\nwhile  i &lt; 5\n    i = i +1\nreturn i</ask>
			<answer>5</answer>
			<types>
				<WHILE /></types>
		</question>
		
		
		
		
		
		
		<question difficulty="1">
			<ask>i = 2\nwhile  i &lt; 5\n    i = i *2\nreturn i</ask>
			<answer>8</answer>
			<types>
				<WHILE /></types>
		</question>
		<question difficulty="1">
			<ask>i = 0\nwhile  i &lt; 10\n    i = i +2\nreturn i</ask>
			<answer>10</answer>
			<types>
				<WHILE /></types>
		</question>
	</return-value-questions>
</questions>
